# Generated by Django 4.1.4 on 2022-12-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='produk_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branda.produk'),
        ),
    ]
